apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release.name }}-deployment
  labels:
    app: {{ .Values.appLabel }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/probe: {{ .Values.release.name }}
spec:
    selector:
        app: {{ .Values.appLabel }}
    ports:
    - name: backend
      port: {{ .Values.service.backend.servicePort }}
      protocol: {{ .Values.service.backend.protocol }}
      targetPort: {{ .Values.service.backend.targetPort }}
    - name: prom
      protocol: {{ .Values.service.prom.protocol }}
      port: {{ .Values.service.prom.servicePort }}
      targetPort: {{ .Values.service.prom.targetPort }}
