kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress-fr
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
    - http:
        paths:
          - path: /events/
            pathType: Prefix
            backend:
              serviceName: backend-dev-deployment
              servicePort: 4567
          - path: /workbooks/
            pathType: Prefix
            backend:
              serviceName: backend-dev-deployment
              servicePort: 4567
          - path: /statistics/
            pathType: Prefix
            backend:
              serviceName: backend-dev-deployment
              servicePort: 4567
          - path: /security/
            pathType: Prefix
            backend:
              serviceName: backend-dev-deployment
              servicePort: 4567
          - path: /
            pathType: Prefix
            backend:
              serviceName: front-dev-deployment
              servicePort: 8080