apiVersion: v1
data:
  config.yml: "server:\r\n  http_listen_port: 9080\r\n  grpc_listen_port: 0\r\n\r\npositions:\r\n  filename: /tmp/positions.yaml\r\n\r\nclients:\r\n  - url: http://loki:3100/loki/api/v1/push\r\n\r\nscrape_configs:\r\n  - job_name: mongo\r\n    static_configs:\r\n    - targets:\r\n        - localhost\r\n      labels:\r\n        job: mongo-dev\r\n        __path__: /var/log/mongodb/*log\r\n"
kind: ConfigMap
metadata:
  name: promtail-mongo-config

