
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.release.name }}-deployment-headless
    labels:
        app: {{ .Values.appLabel }}
spec:
    type: ClusterIP
    selector:
        app: {{ .Values.appLabel }}
    clusterIP: None
    ports:
    - name: mongo
      port: {{ .Values.service.mongo.servicePort }}
      protocol: {{ .Values.service.mongo.protocol }}
      targetPort: {{ .Values.service.mongo.targetPort }}
    - name: prom
      protocol: {{ .Values.service.prom.protocol }}
      port: {{ .Values.service.prom.servicePort }}
      targetPort: {{ .Values.service.prom.targetPort }}

